version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: ecommerce-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - ./backend/.env   # ✅ Load Atlas URI + other configs
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}  # 👈 passed to frontend build
    container_name: ecommerce-frontend
    ports:
      - "5173:80"  # React build served by Nginx
    depends_on:
      - backend
