version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}   # 👈 Use backend service name
    container_name: ecommerce-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
