spring:
  data:
    mongodb:
      uri: mongodb+srv://Krishnasah:<dbPassword>@cluster0.gsivoy1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ecommerce
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email_address
    password: Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

