spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}          # MongoDB connection string from env
      database: ecommerce
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}          # Gmail username from env
    password: ${SPRING_MAIL_PASSWORD}          # Gmail password or app password from env
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api                         # All backend APIs start with /api (e.g., /api/auth/login)

frontend:
  origin: ${FRONTEND_ORIGIN:http://localhost:3000}  # Dynamically read CORS origin from env, default to localhost
